### PR TITLE
chore: fix broken links

### LINKED ISSUE #8011: Broken links in docs
Reviewing https://github.com/patternfly/patternfly/pull/8008 and found a few additional broken links.

1. Updating the URL a little for this - https://github.com/patternfly/patternfly/pull/8008#discussion_r2578892172
2. These two are on the home page and can be removed.

```
URL        `/accessibility-guide'
Name       `Accessibility guide'
Parent URL https://pf-pr-8008.surge.sh/, line 33, col 44177
Real URL   https://pf-pr-8008.surge.sh/accessibility-guide
Check time 3.031 seconds
Size       8KB
Result     Error: 404 Not Found

URL        `/54387135.pdf'
Name       `quick reference sheet.'
Parent URL https://pf-pr-8008.surge.sh/, line 33, col 44260
Real URL   https://pf-pr-8008.surge.sh/54387135.pdf
Check time 3.202 seconds
Size       0B
Result     Error: 404 Not Found
```

3. This was failing - I was able to verify, but it seems OK now? 
```
URL        `/components/text-input-group/html#search-input-group-expandable'
Name       `text input group'
Parent URL https://pf-pr-8008.surge.sh/components/input-group/, line 277, col 24988
Real URL   https://pf-pr-8008.surge.sh/components/text-input-group/html#search-input-group-expandable
Check time 4.061 seconds
Size       8KB
Result     Error: 404 Not Found
```

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/patternfly/patternfly/issues/8011

### CODE REVIEW

File: patternfly-docs/site/pages/index.js [hunk 1]
```diff
@@ -1,12 +1,11 @@
...
 import { PageSection } from '@patternfly/react-core';
-import quickRefPdf from './reference-docs/PF-quick-ref.pdf';
 
 const HomePage = () => (
   <PageSection variant="light">
-    Just getting started? Take a look at the <a href="/contribution">Contribution guide</a> and{' '}
-    <a href="/guidelines">Coding guidelines.</a> Always keep our <a href="/accessibility-guide">Accessibility guide</a>{' '}
-    in mind. Download a <a href={quickRefPdf}>quick reference sheet.</a>
+    Just getting started? Take a look at the <a href="/contribution">contribution guide</a> and{' '}
+    <a href="/guidelines">coding guidelines</a>, and always keep our <a href="https://www.patternfly.org/accessibility/about-accessibility">accessibility fundamentals</a>{' '}
```
Comment (srambach) [inline patternfly-docs/site/pages/index.js]: One thing - the link is "coding guidelines" but the page title is "Development guidelines" - what do you think about making them match?

**Review by srambach — APPROVED** [review]
L 🔗 TM
